services:
  database:
    image: postgres:latest
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - beautypointcollege_db:/var/lib/postgresql/data

volumes:
  beautypointcollege_db:
