services:
  postgres:
    image: postgres:latest
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - beautypointcollege_db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5432
    ports:
      - "8080:5432"
    depends_on:
      - postgres

volumes:
  beautypointcollege_db:
